version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ndaruhes_fresh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  server:
    container_name: go-clean
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8001:8000
    depends_on:
      - database
