version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: PostgresDB
    environment:
      POSTGRES_DB: ndaruhes_fresh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: Elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  server:
    container_name: GoCleanApp
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8100:8100
    depends_on:
      - database
    extra_hosts:
      - "localhost:172.17.0.1"