app:
  Port: 8100
  Name: GoClean
  Locale: en
  Environment: develop
  Key: asfsfdsf
  Debug: true
  MigrateKey:

database:
  host: 172.17.0.1
  port: 5432
  name: ndaruhes_fresh
  username: postgres
  password: root
