app:
  Port: 8100
  Name: go-clean
  Locale: en
  Environment: local
  Key: asfsfdsf
  Debug: true
  MigrateKey:

#database:
#  host: localhost
#  port: 3306
#  name: ndaruhes_fresh
#  username: root
#  password:

database:
  host: localhost
  port: 5432
  name: ndaruhes_fresh
  username: postgres
  password: root
