app:
  Port: 8100
  Name: GoClean
  Locale: en
  Environment: local
  Key: asfsfdsf
  Debug: true
  MigrateKey:

cors:
  AllowOrigins: http://localhost:3000
  AllowHeaders: Origin, Content-Type, Accept
  AllowMethods: GET, POST, PATCH, DELETE
  AllowCredentials: true
  ExposeHeaders: "*"

database:
  Host: localhost
  Port: 5432
  Name: ndaruhes_fresh
  Username: postgres
  Password: root
