app:
  Port: 8100
  Name: GoClean
  Locale: en
  Environment: develop
  Key: asfsfdsf
  Debug: true
  MigrateKey:

cors:
  AllowOrigins: http://localhost:3000
  AllowHeaders: Origin, Content-Type, Accept
  AllowMethods: GET, POST, PATCH, DELETE
  AllowCredentials: true
  ExposeHeaders: "*"

database:
  host: 172.17.0.1
  port: 5432
  name: ndaruhes_fresh
  username: postgres
  password: root
