app:
  Port: 8100
  Name: go-clean
  Locale: en
  #Prefix: JP
  Environment: local
  Key: asfsfdsf
  Debug: true
  MigrateKey:

database:
  host: localhost
  port: 3306
  name: fresh
  username: root
  password:
