app:
  Port: 8100
  Name: GoClean
  Locale: en
  Environment: local
  Key: asfsfdsf
  Debug: true
  MigrateKey:

database:
  host: localhost
  port: 5432
  name: ndaruhes_fresh
  username: postgres
  password: root
